version: '2'
services:
  web:
    build: .
    image: tracking-app
    ports:
      - "5000:5000"
    links:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/trackdb.sql:/docker-entrypoint-initdb.d/trackdb.sql
    environvment:
      POSTGRES_USER: pgdbuser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: trackdb
